//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEL_Delegacje
    {
        public int DEL_DelID { get; set; }
        public int DEL_PraID { get; set; }
        public string DEL_Tytul { get; set; }
        public string DEL_JakiTransport { get; set; }
        public string DEL_MiejscowoscStartu { get; set; }
        public string DEL_MiejscowoscCelu { get; set; }
        public System.DateTime DEL_DzienOd { get; set; }
        public System.DateTime DEL_DzienDo { get; set; }
        public bool DEL_CzyAktywny { get; set; }
        public string DEL_Komentarz { get; set; }
    
        public virtual PRA_Pracownicy PRA_Pracownicy { get; set; }
    }
}
