//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAK_Faktury
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAK_Faktury()
        {
            this.POF_PozycjeFaktury = new HashSet<POF_PozycjeFaktury>();
        }
    
        public int FAK_FakID { get; set; }
        public System.DateTime FAK_DataWystawienia { get; set; }
        public Nullable<int> FAK_KliID { get; set; }
        public Nullable<int> FAK_SppID { get; set; }
        public Nullable<bool> FAK_CzyAktywny { get; set; }
    
        public virtual KLI_Klienci KLI_Klienci { get; set; }
        public virtual SPP_SposobPlatnosci SPP_SposobPlatnosci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POF_PozycjeFaktury> POF_PozycjeFaktury { get; set; }
    }
}
