//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOT_Fotorejestracja
    {
        public int FOT_FotID { get; set; }
        public System.TimeSpan FOT_GodzinaWejscia { get; set; }
        public System.TimeSpan FOT_GodzinaWyjscia { get; set; }
        public int FOT_PraID { get; set; }
        public System.DateTime FOT_DataWejscia { get; set; }
        public System.DateTime FOT_DataWyjscia { get; set; }
        public Nullable<bool> FOT_CzyAktywny { get; set; }
    
        public virtual PRA_Pracownicy PRA_Pracownicy { get; set; }
    }
}
