//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRP_GrafikPracy
    {
        public int GRP_GrpID { get; set; }
        public int GRP_PraID { get; set; }
        public Nullable<System.DateTime> GRP_Dzien { get; set; }
        public string GRP_Zmiana { get; set; }
        public bool GRP_CzyAktywny { get; set; }
    
        public virtual PRA_Pracownicy PRA_Pracownicy { get; set; }
    }
}
