//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JEM_JednostkiMiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JEM_JednostkiMiary()
        {
            this.POF_PozycjeFaktury = new HashSet<POF_PozycjeFaktury>();
        }
    
        public int JEM_JemID { get; set; }
        public string JEM_Nazwa { get; set; }
        public string JEM_Opis { get; set; }
        public bool JEM_CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POF_PozycjeFaktury> POF_PozycjeFaktury { get; set; }
    }
}
