//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAT_KategorieTowarow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KAT_KategorieTowarow()
        {
            this.TOW_Towary = new HashSet<TOW_Towary>();
        }
    
        public int KAT_KatID { get; set; }
        public string KAT_Nazwa { get; set; }
        public string KAT_Opis { get; set; }
        public bool KAT_CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOW_Towary> TOW_Towary { get; set; }
    }
}
