//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLI_Klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KLI_Klienci()
        {
            this.FAK_Faktury = new HashSet<FAK_Faktury>();
        }
    
        public int KLI_KliID { get; set; }
        public string KLI_Nazwa { get; set; }
        public string KLI_Adres { get; set; }
        public string KLI_Telefon { get; set; }
        public bool KLI_CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAK_Faktury> FAK_Faktury { get; set; }
    }
}
