//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UrlopyEntities : DbContext
    {
        public UrlopyEntities()
            : base("name=UrlopyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEL_Delegacje> DEL_Delegacje { get; set; }
        public virtual DbSet<DZI_Dzialy> DZI_Dzialy { get; set; }
        public virtual DbSet<FAK_Faktury> FAK_Faktury { get; set; }
        public virtual DbSet<FOT_Fotorejestracja> FOT_Fotorejestracja { get; set; }
        public virtual DbSet<GRP_GrafikPracy> GRP_GrafikPracy { get; set; }
        public virtual DbSet<JAP_JezykAplikacji> JAP_JezykAplikacji { get; set; }
        public virtual DbSet<JEM_JednostkiMiary> JEM_JednostkiMiary { get; set; }
        public virtual DbSet<KAT_KategorieTowarow> KAT_KategorieTowarow { get; set; }
        public virtual DbSet<KLI_Klienci> KLI_Klienci { get; set; }
        public virtual DbSet<POF_PozycjeFaktury> POF_PozycjeFaktury { get; set; }
        public virtual DbSet<PRA_Pracownicy> PRA_Pracownicy { get; set; }
        public virtual DbSet<RUR_RodzajeUrlopow> RUR_RodzajeUrlopow { get; set; }
        public virtual DbSet<SPP_SposobPlatnosci> SPP_SposobPlatnosci { get; set; }
        public virtual DbSet<STC_StrefaCzasowa> STC_StrefaCzasowa { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TOW_Towary> TOW_Towary { get; set; }
        public virtual DbSet<URL_Urlopy> URL_Urlopy { get; set; }
        public virtual DbSet<WUR_WnioskiUrlopowe> WUR_WnioskiUrlopowe { get; set; }
        public virtual DbSet<ZDA_Zdarzenia> ZDA_Zdarzenia { get; set; }
    }
}
