//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class POF_PozycjeFaktury
    {
        public int POF_PofID { get; set; }
        public int POF_TowID { get; set; }
        public int POF_FakID { get; set; }
        public int POF_JemID { get; set; }
        public string POF_Nazwa { get; set; }
        public int POF_Ilosc { get; set; }
        public decimal POF_Cena { get; set; }
        public decimal POF_Rabat { get; set; }
        public decimal POF_Marza { get; set; }
        public bool POF_CzyAktywny { get; set; }
    
        public virtual FAK_Faktury FAK_Faktury { get; set; }
        public virtual JEM_JednostkiMiary JEM_JednostkiMiary { get; set; }
        public virtual TOW_Towary TOW_Towary { get; set; }
    }
}
