//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRA_Pracownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRA_Pracownicy()
        {
            this.DEL_Delegacje = new HashSet<DEL_Delegacje>();
            this.FOT_Fotorejestracja = new HashSet<FOT_Fotorejestracja>();
            this.GRP_GrafikPracy = new HashSet<GRP_GrafikPracy>();
            this.URL_Urlopy = new HashSet<URL_Urlopy>();
            this.WUR_WnioskiUrlopowe = new HashSet<WUR_WnioskiUrlopowe>();
            this.ZDA_Zdarzenia = new HashSet<ZDA_Zdarzenia>();
        }
    
        public int PRA_PraID { get; set; }
        public string PRA_Imie { get; set; }
        public Nullable<int> PRA_DziID { get; set; }
        public string PRA_Nazwisko { get; set; }
        public string PRA_ILogin { get; set; }
        public byte[] PRA_Haslo { get; set; }
        public string PRA_UrlZdjecia { get; set; }
        public Nullable<int> PRA_StcID { get; set; }
        public string PRA_Email { get; set; }
        public string PRA_Telefon { get; set; }
        public string PRA_Ulica { get; set; }
        public string PRA_Miasto { get; set; }
        public string PRA_KodPocztowy { get; set; }
        public Nullable<bool> PRA_CzyZatrudniony { get; set; }
        public Nullable<int> PRA_JapID { get; set; }
        public Nullable<bool> PRA_ZgodaMarketingowa { get; set; }
        public string PRA_Wojewodztwo { get; set; }
        public string PRA_NrDomu { get; set; }
        public string PRA_Gmina { get; set; }
        public Nullable<bool> PRA_CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEL_Delegacje> DEL_Delegacje { get; set; }
        public virtual DZI_Dzialy DZI_Dzialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOT_Fotorejestracja> FOT_Fotorejestracja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRP_GrafikPracy> GRP_GrafikPracy { get; set; }
        public virtual JAP_JezykAplikacji JAP_JezykAplikacji { get; set; }
        public virtual STC_StrefaCzasowa STC_StrefaCzasowa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URL_Urlopy> URL_Urlopy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WUR_WnioskiUrlopowe> WUR_WnioskiUrlopowe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZDA_Zdarzenia> ZDA_Zdarzenia { get; set; }
    }
}
