//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUR_RodzajeUrlopow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUR_RodzajeUrlopow()
        {
            this.URL_Urlopy = new HashSet<URL_Urlopy>();
            this.WUR_WnioskiUrlopowe = new HashSet<WUR_WnioskiUrlopowe>();
        }
    
        public int RUR_RurID { get; set; }
        public string RUR_Nazwa { get; set; }
        public Nullable<bool> RUR_CzyAktywny { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URL_Urlopy> URL_Urlopy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WUR_WnioskiUrlopowe> WUR_WnioskiUrlopowe { get; set; }
    }
}
