//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOW_Towary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOW_Towary()
        {
            this.POF_PozycjeFaktury = new HashSet<POF_PozycjeFaktury>();
        }
    
        public int TOW_TowID { get; set; }
        public string TOW_Nazwa { get; set; }
        public string TOW_Kod { get; set; }
        public string TOW_Opis { get; set; }
        public int TOW_KatID { get; set; }
        public int TOW_StanIlosciowy { get; set; }
        public string TOW_Zdjecie { get; set; }
        public bool TOW_CzyAktywny { get; set; }
    
        public virtual KAT_KategorieTowarow KAT_KategorieTowarow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POF_PozycjeFaktury> POF_PozycjeFaktury { get; set; }
    }
}
