//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL_Urlopy
    {
        public int URL_UrlID { get; set; }
        public Nullable<int> URL_PraID { get; set; }
        public DateTime URL_DzienOd { get; set; }
        public DateTime URL_DzienDo { get; set; }
        public Nullable<int> URL_RurID { get; set; }
        public Nullable<bool> URL_CzyAktywny { get; set; }
    
        public virtual PRA_Pracownicy PRA_Pracownicy { get; set; }
        public virtual RUR_RodzajeUrlopow RUR_RodzajeUrlopow { get; set; }
    }
}
