//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlopyApiXaml.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZDA_Zdarzenia
    {
        public int ZDA_ZdaID { get; set; }
        public string ZDA_Nazwa { get; set; }
        public Nullable<bool> ZDA_CzyAktywny { get; set; }
        public Nullable<int> ZDA_PraID { get; set; }
    
        public virtual PRA_Pracownicy PRA_Pracownicy { get; set; }
    }
}
